FROM apache/superset:latest

USER root

RUN apt-get update && apt-get install -y libaio1 python3-dev build-essential \
    && /app/.venv/bin/python -m ensurepip \
    && /app/.venv/bin/python -m pip install oracledb

USER superset

