name: apt_mart
version: "1.0.0"
profile: apt_mart

model-paths: ["models"]

models:
  apt_mart:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

